
name: main

on:
  push:
    branches:
      - main
    paths:
      - api/**
      - controllers/**
      - Dockerfile
      - main.go
      - go.mod
      - go.sum
      - .dockerignore
      - Makefile
      - .github/**

env:
  PACKAGE: docker.pkg.github.com/russtanevich/kbt/operator
  IMG: ${PACKAGE}:${GITHUB_SHA}

jobs:
  build-image:
    name: build-image
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: russtanevich/kbt
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: dockerlogin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: russtanevich
        run: docker login https://docker.pkg.github.com -u ${GITHUB_USER} --password ${GITHUB_TOKEN}
      - name: build
        run: make docker-build
      - name: push
        run: make docker-push
